shell_uuid = 'gnome-customizer@io.github.gnomecustomizer'
shell_dir = datadir / 'gnome-shell/extensions' / shell_uuid
install_data('metadata.json', 'extension.js', 'stylesheet.css', install_dir: shell_dir)
install_data('schemas/io.github.gnomecustomizer.shell.gschema.xml', install_dir: shell_dir / 'schemas')
